[versions]
quarkus = "3.15.1"
muyun = "0.1.1"
caffeine = "3.1.8"
testcontainers = "1.20.1"

[libraries]
quarkus-platform-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
muyun-core = { module = "net.ximatai.muyun:muyun-core", version.ref = "muyun" }
muyun-database-std = { module = "net.ximatai.muyun:muyun-database-std", version.ref = "muyun" }
muyun-platform = { module = "net.ximatai.muyun:muyun-platform", version.ref = "muyun" }
muyun-proxy = { module = "net.ximatai.muyun:muyun-proxy", version.ref = "muyun" }
muyun-log = { module = "net.ximatai.muyun:muyun-log", version.ref = "muyun" }
muyun-authorization = { module = "net.ximatai.muyun:muyun-authorization", version.ref = "muyun" }
muyun-fileserver = { module = "net.ximatai.muyun:muyun-fileserver", version.ref = "muyun" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
